apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/operators/openshift-pipelines
    repoURL: https://github.com/dwakeman/gitops-cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true