apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redhat-sso
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rh-sso
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/operators/redhat-sso
    repoURL: https://github.com/dwakeman/gitops-cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true