apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-openshift-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "100"    
spec:
  destination:
    namespace: ocs
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 3-infra/namespaces/openshift-pipelines
    repoURL: https://github.com/dwakeman/gitops-cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true